//package Redland;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.19
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

class RedlandPINVOKE {

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_world")]
  public static extern IntPtr librdf_new_world();

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_world")]
  public static extern void librdf_free_world(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_world_open")]
  public static extern void librdf_world_open(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_init_world")]
  public static extern void librdf_init_world(string jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_destroy_world")]
  public static extern void librdf_destroy_world();

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_iterator")]
  public static extern void librdf_free_iterator(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_iterator_have_elements")]
  public static extern int librdf_iterator_have_elements(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_iterator_end")]
  public static extern int librdf_iterator_end(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_iterator_get_object")]
  public static extern IntPtr librdf_iterator_get_object(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_iterator_get_context")]
  public static extern IntPtr librdf_iterator_get_context(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_iterator_next")]
  public static extern int librdf_iterator_next(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_uri")]
  public static extern IntPtr librdf_new_uri(IntPtr jarg1, string jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_uri_from_uri")]
  public static extern IntPtr librdf_new_uri_from_uri(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_uri_from_filename")]
  public static extern IntPtr librdf_new_uri_from_filename(IntPtr jarg1, string jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_uri")]
  public static extern void librdf_free_uri(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_uri_to_string")]
  public static extern string librdf_uri_to_string(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_uri_equals")]
  public static extern int librdf_uri_equals(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_node")]
  public static extern IntPtr librdf_new_node(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_node_from_uri_string")]
  public static extern IntPtr librdf_new_node_from_uri_string(IntPtr jarg1, string jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_node_from_uri")]
  public static extern IntPtr librdf_new_node_from_uri(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_node_from_literal")]
  public static extern IntPtr librdf_new_node_from_literal(IntPtr jarg1, string jarg2, string jarg3, int jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_node_from_typed_literal")]
  public static extern IntPtr librdf_new_node_from_typed_literal(IntPtr jarg1, string jarg2, string jarg3, IntPtr jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_node_from_node")]
  public static extern IntPtr librdf_new_node_from_node(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_node_from_blank_identifier")]
  public static extern IntPtr librdf_new_node_from_blank_identifier(IntPtr jarg1, string jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_node")]
  public static extern void librdf_free_node(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_get_uri")]
  public static extern IntPtr librdf_node_get_uri(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_get_type")]
  public static extern int librdf_node_get_type(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_get_literal_value")]
  public static extern string librdf_node_get_literal_value(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_get_literal_value_as_latin1")]
  public static extern string librdf_node_get_literal_value_as_latin1(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_get_literal_value_language")]
  public static extern string librdf_node_get_literal_value_language(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_get_literal_value_datatype_uri")]
  public static extern IntPtr librdf_node_get_literal_value_datatype_uri(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_get_literal_value_is_wf_xml")]
  public static extern int librdf_node_get_literal_value_is_wf_xml(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_to_string")]
  public static extern string librdf_node_to_string(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_get_blank_identifier")]
  public static extern string librdf_node_get_blank_identifier(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_is_resource")]
  public static extern int librdf_node_is_resource(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_is_literal")]
  public static extern int librdf_node_is_literal(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_is_blank")]
  public static extern int librdf_node_is_blank(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_node_equals")]
  public static extern int librdf_node_equals(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_statement")]
  public static extern IntPtr librdf_new_statement(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_statement_from_statement")]
  public static extern IntPtr librdf_new_statement_from_statement(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_statement_from_nodes")]
  public static extern IntPtr librdf_new_statement_from_nodes(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3, IntPtr jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_statement")]
  public static extern void librdf_free_statement(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_statement_get_subject")]
  public static extern IntPtr librdf_statement_get_subject(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_statement_set_subject")]
  public static extern void librdf_statement_set_subject(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_statement_get_predicate")]
  public static extern IntPtr librdf_statement_get_predicate(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_statement_set_predicate")]
  public static extern void librdf_statement_set_predicate(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_statement_get_object")]
  public static extern IntPtr librdf_statement_get_object(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_statement_set_object")]
  public static extern void librdf_statement_set_object(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_statement_to_string")]
  public static extern string librdf_statement_to_string(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_model")]
  public static extern IntPtr librdf_new_model(IntPtr jarg1, IntPtr jarg2, string jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_model_with_options")]
  public static extern IntPtr librdf_new_model_with_options(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_model_from_model")]
  public static extern IntPtr librdf_new_model_from_model(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_model")]
  public static extern void librdf_free_model(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_size")]
  public static extern int librdf_model_size(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_add")]
  public static extern int librdf_model_add(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3, IntPtr jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_add_typed_literal_statement")]
  public static extern int librdf_model_add_typed_literal_statement(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3, string jarg4, string jarg5, IntPtr jarg6);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_add_statement")]
  public static extern int librdf_model_add_statement(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_add_statements")]
  public static extern int librdf_model_add_statements(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_remove_statement")]
  public static extern int librdf_model_remove_statement(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_contains_statement")]
  public static extern int librdf_model_contains_statement(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_as_stream")]
  public static extern IntPtr librdf_model_as_stream(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_serialise")]
  public static extern IntPtr librdf_model_serialise(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_find_statements")]
  public static extern IntPtr librdf_model_find_statements(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_get_sources")]
  public static extern IntPtr librdf_model_get_sources(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_get_arcs")]
  public static extern IntPtr librdf_model_get_arcs(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_get_targets")]
  public static extern IntPtr librdf_model_get_targets(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_get_source")]
  public static extern IntPtr librdf_model_get_source(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_get_arc")]
  public static extern IntPtr librdf_model_get_arc(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_get_target")]
  public static extern IntPtr librdf_model_get_target(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_context_add_statement")]
  public static extern int librdf_model_context_add_statement(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_context_add_statements")]
  public static extern int librdf_model_context_add_statements(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_context_remove_statement")]
  public static extern int librdf_model_context_remove_statement(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_context_remove_statements")]
  public static extern int librdf_model_context_remove_statements(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_context_as_stream")]
  public static extern IntPtr librdf_model_context_as_stream(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_context_serialize")]
  public static extern IntPtr librdf_model_context_serialize(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_model_sync")]
  public static extern void librdf_model_sync(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_storage")]
  public static extern IntPtr librdf_new_storage(IntPtr jarg1, string jarg2, string jarg3, string jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_storage_from_storage")]
  public static extern IntPtr librdf_new_storage_from_storage(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_storage")]
  public static extern void librdf_free_storage(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_parser")]
  public static extern IntPtr librdf_new_parser(IntPtr jarg1, string jarg2, string jarg3, IntPtr jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_parser")]
  public static extern void librdf_free_parser(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_parser_parse_as_stream")]
  public static extern IntPtr librdf_parser_parse_as_stream(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_parser_parse_into_model")]
  public static extern int librdf_parser_parse_into_model(IntPtr jarg1, IntPtr jarg2, IntPtr jarg3, IntPtr jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_parser_parse_string_as_stream")]
  public static extern IntPtr librdf_parser_parse_string_as_stream(IntPtr jarg1, string jarg2, IntPtr jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_parser_parse_string_into_model")]
  public static extern int librdf_parser_parse_string_into_model(IntPtr jarg1, string jarg2, IntPtr jarg3, IntPtr jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_parser_get_feature")]
  public static extern string librdf_parser_get_feature(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_parser_set_feature")]
  public static extern int librdf_parser_set_feature(IntPtr jarg1, IntPtr jarg2, string jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_new_serializer")]
  public static extern IntPtr librdf_new_serializer(IntPtr jarg1, string jarg2, string jarg3, IntPtr jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_serializer")]
  public static extern void librdf_free_serializer(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_serializer_serialize_model_to_file")]
  public static extern int librdf_serializer_serialize_model_to_file(IntPtr jarg1, string jarg2, IntPtr jarg3, IntPtr jarg4);

  [DllImport("Redland", EntryPoint="CSharp_librdf_serializer_get_feature")]
  public static extern string librdf_serializer_get_feature(IntPtr jarg1, IntPtr jarg2);

  [DllImport("Redland", EntryPoint="CSharp_librdf_serializer_set_feature")]
  public static extern int librdf_serializer_set_feature(IntPtr jarg1, IntPtr jarg2, string jarg3);

  [DllImport("Redland", EntryPoint="CSharp_librdf_free_stream")]
  public static extern void librdf_free_stream(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_stream_end")]
  public static extern int librdf_stream_end(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_stream_next")]
  public static extern int librdf_stream_next(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_stream_get_object")]
  public static extern IntPtr librdf_stream_get_object(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_stream_get_context")]
  public static extern IntPtr librdf_stream_get_context(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_internal_test_error")]
  public static extern void librdf_internal_test_error(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_librdf_internal_test_warning")]
  public static extern void librdf_internal_test_warning(IntPtr jarg1);

  [DllImport("Redland", EntryPoint="CSharp_get_redland_copyright_string")]
  public static extern string get_redland_copyright_string();

  [DllImport("Redland", EntryPoint="CSharp_get_redland_version_string")]
  public static extern string get_redland_version_string();

  [DllImport("Redland", EntryPoint="CSharp_get_redland_version_major")]
  public static extern int get_redland_version_major();

  [DllImport("Redland", EntryPoint="CSharp_get_redland_version_minor")]
  public static extern int get_redland_version_minor();

  [DllImport("Redland", EntryPoint="CSharp_get_redland_version_release")]
  public static extern int get_redland_version_release();
}
