# This file was automatically generated by SWIG
package RDF::Redland::CORE;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package RDF::Redland::CORE;
bootstrap RDF::Redland::CORE;
package RDF::Redland::CORE;
@EXPORT = qw( );
1;
