#!/bin/sh
#
# $Id: redland-src-config.in 8501 2005-12-21 05:36:18Z cmdjb $
#
# Copyright (C) 2002-2004 David Beckett http://purl.org/net/dajobe/
# Copyright (C) 2002-2004 University of Bristol, UK http://www.bristol.ac.uk/
# 
# This package is Free Software and part of Redland http://librdf.org/
# 
# It is licensed under the following three licenses as alternatives:
#   1. GNU Lesser General Public License (LGPL) V2.1 or any newer version
#   2. GNU General Public License (GPL) V2 or any newer version
#   3. Apache License, V2.0 or any newer version
# 
# You may not use this file except in compliance with at least one of
# the above three licenses.
# 
# See LICENSE.html or LICENSE.txt at the top of this package for the
# complete terms and further detail along with the license texts for
# the licenses in COPYING.LIB, COPYING and LICENSE-2.0.txt respectively.
# 
# 
#

usage()
{
	cat<<EOF
fUsage: redland-src-config [OPTION]

known values for OPTION are:

  --cflags              print pre-processor and compiler flags
  --help                display this help and exit
  --libs                print library linking information
  --libtool-libs        print linking information for use with libtool
  --version             output version information
  --run COMMAND         run the COMMAND with the shared libraries for
                        the source tree
  --swig                display the SWIG interface file
  --version             output version information
  --version-decimal     output version as a decimal integer
EOF
  exit $1
}


if test $# -eq 0; then
  usage 1 1>&2
fi


while test $# -gt 0; do
  case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
  esac

  case $1 in
    --version)
      echo 1.0.5
      exit 0
      ;;
    --cflags)
      echo_cflags=yes
      ;;
    --libs)
      echo_libs=yes
      ;;
    --libtool-libs)
      echo_libtool_libs=yes
      ;;
    --help|--usage)
      usage 0
      ;;
    --run)
      lpath=/home/dajobe/dev/redland/perl/redland/librdf/.libs
      if test -d .libs; then
        lpath=".libs:$lpath"
      fi
      if test system = internal; then
        lpath="$lpath:/home/dajobe/dev/redland/perl/redland/raptor/.libs"
      else
        raptor_prefix=`raptor-config --prefix`
        lpath="$lpath:$raptor_prefix/lib"
      fi
      if test system = internal; then
        lpath="$lpath:/home/dajobe/dev/redland/perl/redland/rasqal/.libs"
      else
        rasqal_prefix=`rasqal-config --prefix`
        lpath="$lpath:$rasqal_prefix/lib"
      fi
      if test `uname` = Darwin; then
        DYLD_LIBRARY_PATH=$lpath:$DYLD_LIBRARY_PATH
        export DYLD_LIBRARY_PATH
      else
        LD_LIBRARY_PATH=$lpath:$LD_LIBRARY_PATH
        export LD_LIBRARY_PATH
      fi
      shift
      exec ${1+"$@"}
      ;;

    --swig)
      echo_swig=yes
      ;;

    --version)
      echo 1.0.5
      exit 0
      ;;

    --version-decimal)
      echo 10005
      exit 0
      ;;

    *)
      usage 1 1>&2
      ;;
  esac

  shift
done

if test system = internal; then
  raptor_config=/home/dajobe/dev/redland/perl/redland/raptor/raptor-src-config
  if test ! -r $raptor_config; then
    echo "redland-src-config: Source tree not configured - no raptor-src-config, exiting" 1>&2
    exit 0
  fi
else
  raptor_config=raptor-config
fi

if test system = internal; then
  rasqal_config=/home/dajobe/dev/redland/perl/redland/rasqal/rasqal-src-config
  if test ! -r $rasqal_config; then
    echo "redland-src-config: Source tree not configured - no rasqal-src-config, exiting" 1>&2
    exit 0
  fi
else
  rasqal_config=rasqal-config
fi

if test "$echo_cflags" = "yes"; then
  echo -I/home/dajobe/dev/redland/perl/redland/librdf `$rasqal_config --cflags` `$raptor_config --cflags`
fi
if test "$echo_libtool_libs" = "yes"; then
  echo /home/dajobe/dev/redland/perl/redland/librdf/librdf.la
fi

if test "$echo_libs" = "yes"; then
  echo -L/home/dajobe/dev/redland/perl/redland/librdf/.libs -lrdf  -L/usr/lib -lrasqal -L/usr/lib -lraptor -L/usr/lib -lcurl -L/usr/lib -lgssapi_krb5 -lkrb5 -lk5crypto -lkrb5support -lcom_err -lresolv -lidn -lssl -lcrypto -ldl -lssl -lcrypto -lz -L/usr/lib -lxml2 -L/usr/lib -lxslt -lxml2 -L/usr/lib -lraptor -L/usr/lib -lcurl -L/usr/lib -lgssapi_krb5 -lkrb5 -lk5crypto -lkrb5support -lcom_err -lresolv -lidn -lssl -lcrypto -ldl -lssl -lcrypto -lz -L/usr/lib -lxml2 -L/usr/lib -lxslt -lxml2    -ldb-4.4 -lcrypto -L/usr/lib/mysql -lmysqlclient -lsqlite3   -L/usr/lib -lpq `$rasqal_config --libs` `$raptor_config --libs`
fi

if test "$echo_swig" = "yes"; then  
  echo /home/dajobe/dev/redland/perl/redland/Redland.i
fi
